-- schema.sql
-- Run these commands in the Supabase SQL Editor to set up the database.

-- 1. Create the 'sessions' table
-- This table stores high-level metadata about each chat session.
create table public.sessions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  user_id text,
  start_time timestamp with time zone default timezone('utc'::text, now()),
  end_time timestamp with time zone,
  summary text
);

-- 2. Create the 'logs' table
-- This table stores the granular history of every message sent and received.
create table public.logs (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sender text not null, -- 'user' or 'ai'
  message text,
  timestamp timestamp with time zone default timezone('utc'::text, now())
);

-- 3. (Optional) Enable Row Level Security (RLS)
-- Ideally, you would enable RLS here, but for this demo, we keep it open 
-- to ensure the API key works without complex policy setup.
alter table public.sessions enable row level security;
alter table public.logs enable row level security;

-- Allow public access for this demo (Simulates service role access)
create policy "Allow all access" on public.sessions for all using (true);
create policy "Allow all access" on public.logs for all using (true);